#!/usr/bin/with-contenv bash

echo "Starting UnicornTranscoder"

# exec s6-setuidgid plex /bin/sh -c 'sleep 1000000'
exec s6-setuidgid plex /bin/sh -c 'DEBUG=* node /opt/UnicornLoadBalancer-2.4.0/index.js'
