#!/usr/bin/with-contenv bash

echo "Starting UnicornLoadBalancer."

export PLEX_PATH_SESSIONS="/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions"
export DATABASE_SQLITE_PATH="/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"

exec s6-setuidgid plex /bin/sh -c 'cd /opt/UnicornLoadBalancer* && npm start'
